src/main/java/edu/agh/sius/bean/Form.java
package edu.agh.sius.bean;

import java.util.Scanner;

/**
 * Klasa reprezentująca formularz - jego pola i walidacją stosowaną do tych pól.
 * Pola formularza przechowywane są w zmiennej "data" - każda nowa linia to osobne pole.
 * Walidacja w analogiczny sposób.
 */
public class Form {

    // dostępne typy danych przechowywanych w formularzach
    public static final String[] INPUT_TYPES = {
        "color", "date", "datetime", "datetime-local", "email", "month", "number", "range",
        "search", "tel", "time", "url", "week"
    };
    
	private String name;
	private String data;
    private String validation;
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getData() {
		return data;
	}
	public void setData(String data) {
		this.data = data;
	}
    public String getValidation() {
        return validation;
    }
    public void setValidation(String validation) {
        this.validation = validation;
    }
    public String getHtmlData() {
        String html = "";
        Scanner scanner = new Scanner(data);
        while (scanner.hasNextLine()) {
            String line = scanner.nextLine();
            if (line.contains(",")) {
                String[] attrs = line.split(",");
                String element = attrs[0];
                String type = attrs[1];
                String name = attrs[2];
                String label = attrs[3];
                html += "<label for='id_" + name + "'>" + label + "</label>";
                html += "<" + element + " id='id_" + name + "' name='" + name + "' type='" + type + "' />";
            }
        }
        scanner.close();
        return html;
    }
    public String getJsValidation() {
        String js = "";
        Scanner scanner = new Scanner(validation);
        while (scanner.hasNextLine()) {
            String line = scanner.nextLine();
            if (line.contains(",")) {
                String[] attrs = line.split(",");
                String type = attrs[0];
                String name = attrs[1];
                if (type.equals("range")) {
                    String min = attrs[2];
                    String max = attrs[3];
                    js += "$('[name=" + name + "]').change(function() {" +
                            "if ($(this).val() < " + min + " || $(this).val() > " + max + ") {" +
                                "$(this).addClass('error');" +
                            "} else {" +
                                "$(this).removeClass('error');" +
                            "}" +
                          "});";
                }
            }
        }
        scanner.close();
        return js;
    }

}

src/main/java/edu/agh/sius/controller/FormController.java
package edu.agh.sius.controller;

import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import edu.agh.sius.bean.Form;

import java.util.LinkedList;
import java.util.List;

/**
 * Kontroler odpowiedzialny za tworzenie i listowanie formularzy.
 */
@Controller
public class FormController {

    private List<Form> forms = new LinkedList<Form>();

    // lista formularzy
    @RequestMapping(value = "/", method = RequestMethod.GET)
    public ModelAndView getFormList() {
        return new ModelAndView("list", "forms", forms);
    }

    // foremka do tworzenia nowego formularza
	@RequestMapping(value = "/create", method = RequestMethod.GET)
	public ModelAndView getEmptyForm() {
		ModelAndView modelAndView = new ModelAndView("create", "command", new Form());
        modelAndView.addObject("inputTypes", Form.INPUT_TYPES);
        return modelAndView;
	}

    // tworzenie formularzy
	@RequestMapping(value = "/create", method = RequestMethod.POST)
    public ModelAndView createForm(@ModelAttribute("create") Form form, BindingResult result) {
        forms.add(form);
        return new ModelAndView("show", "form", form);
    }

    // prezentowanie formularza za pomocą HTML i JS
    @RequestMapping(value = "/show/{formId}", method = RequestMethod.GET)
    public ModelAndView showForm(@PathVariable String formId) {
        return new ModelAndView("show", "form", forms.get(Integer.parseInt(formId)));
    }

}

src/main/webapp/WEB-INF/pages/create.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<!doctype html>
<html>
<head>
<link href="<c:url value="/resources/bootstrap/css/bootstrap.min.css" />" rel="stylesheet">
<link href="<c:url value="/resources/css/main.css" />" rel="stylesheet">
<script src="<c:url value="/resources/js/jquery.1.10.2.min.js" />"></script>
<script src="<c:url value="/resources/bootstrap/js/bootstrap.min.js" />"></script>
<script src="<c:url value="/resources/js/main.js" />"></script>
</head>
<body>

    <div class="navbar navbar-inverse">
        <div class="navbar-inner">
            <a class="brand" href="/">Form Builder</a>
            <ul class="nav">
                <li><a href="/">Home</a></li>
                <li class="active"><a href="create.html">Create</a></li>
            </ul>
        </div>
    </div>
    
    <div class="container">
		<form:form method="POST" id="form" commandName="command" action="create.html">
		    <div style="">
		    	<label for="id_form_name">Form name: </label>
			    <form:input path="name" id="id_form_name" />
			    <div class="<%--hide--%>">
                    <form:textarea path="data" />
                    <form:textarea path="validation" />
                </div>
		    </div>
		    <input type="submit" value="Save" class="btn btn-primary" />
		</form:form>
		
		<div class="row">
			<div id="toolbox" class="span4">
				<h2>Add input</h2>

                <label for="id_input_label">Label: </label>
				<input id="id_input_label" name="input_label" type="text" />

                <label for="id_input_label">Name: </label>
				<input id="id_input_name" name="input_name" type="text" /><br>

                <label for="id_input_type">Type: </label>
                <select id="id_input_type" name="input_type">
                    <c:forEach items="${inputTypes}" var="type">
                        <option value="${type}">${type}</option>
                    </c:forEach>
				</select>

                <div id="validation_inputs">
                    <div data-type="number" style="display: none">
                        <label for="id_input_value_min">Min: </label>
                        <input id="id_input_value_min" name="value_min" type="text" /><br>

                        <label for="id_input_value_max">Max: </label>
                        <input id="id_input_value_max" name="value_max" type="text" /><br>
                    </div>
                </div>

                <br>
				<a href="#add-input" class="btn" style="float: left" data-type="text">Add</a>
			</div>
			
			<div class="span8">
				<h2>Preview</h2>
				<div id="preview" class="span8">
				</div>
			</div>
		</div>
    </div>
	
</body>
</html>

src/main/webapp/WEB-INF/pages/list.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<!doctype html>
<html>
<head>
<link href="<c:url value="/resources/bootstrap/css/bootstrap.min.css" />" rel="stylesheet">
<link href="<c:url value="/resources/css/main.css" />" rel="stylesheet">
<script src="<c:url value="/resources/js/jquery.1.10.2.min.js" />"></script>
<script src="<c:url value="/resources/bootstrap/js/bootstrap.min.js" />"></script>
<script src="<c:url value="/resources/js/main.js" />"></script>
</head>
<body>

    <div class="navbar navbar-inverse">
	    <div class="navbar-inner">
	        <a class="brand" href="/">Form Builder</a>
	        <ul class="nav">
	           <li><a href="/">Home</a></li>
	           <li class="active"><a href="create.html">Create</a></li>
	        </ul>
	    </div>
	</div>
    
    <div class="container">

        <h1>Forms</h1>

        <c:choose>
            <c:when test="${not empty forms}">
                <ul>
                    <c:forEach items="${forms}" var="form" varStatus="status">
                        <li><a href="/show/${status.index}">${form.name}</a></li>
                    </c:forEach>
                </ul>
            </c:when>
            <c:otherwise>
                There are no forms. <a href="create.html">Create new form</a>.
            </c:otherwise>
        </c:choose>

    </div>
	
</body>
</html>

src/main/webapp/WEB-INF/pages/show.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<!doctype html>
<html>
<head>
<link href="<c:url value="/resources/bootstrap/css/bootstrap.min.css" />" rel="stylesheet">
<link href="<c:url value="/resources/css/main.css" />" rel="stylesheet">
<script src="<c:url value="/resources/js/jquery.1.10.2.min.js" />"></script>
<script src="<c:url value="/resources/bootstrap/js/bootstrap.min.js" />"></script>
<script src="<c:url value="/resources/js/main.js" />"></script>
</head>
<body>

    <div class="navbar navbar-inverse">
        <div class="navbar-inner">
            <a class="brand" href="/">Form Builder</a>
            <ul class="nav">
                <li><a href="/">Home</a></li>
                <li class="active"><a href="create.html">Create</a></li>
            </ul>
        </div>
    </div>
    
    <div class="container">

        <script>
            $(function() {
                ${form.jsValidation}
            });
        </script>
	
		<div class="row">
			<h2>${form.name}</h2>
			<div id="form-data">${form.htmlData}</div>
		</div>
		
	</div>
	
</body>
</html>